---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-10.04
- name: ubuntu-12.04
- name: centos-5.9
- name: centos-6.4

suites:
- name: default
  run_list:
    - recipe[multipath::default]
  attributes:
    multipath:
      storage_type: "purestorage"
      aliases: [ "mysql:3624a937017bcaa64842651bf00015fea" ]
- name: customized
  run_list:
    - recipe[multipath::default]
  attributes:
    multipath:
      storage_type: "customized"
      defaults:
        queue_without_daemon: "no"
        max_fds: "max"
      devices:
        OPEN-d*:
          vendor: "\"HP\""
          path_grouping_policy: "multibus"
          rr_min_io: 1000
        HSV200:
          vendor: "\"HP\""
          path_grouping_policy: "group_by_prio"
          rr_min_io: 100
        Invista:
          vendor: "\"EMC\""
          path_grouping_policy: "multibus"
          product_blacklist: "\"LUNZ\""
